

service: natter

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-2

functions:
  natter:
    handler: handler.natter
    events:
      - http:
          path: natter
          method: post
          cors: true
  test:
    handler: test.handler
    environment:
      GATEWAY_API: 
        Ref: ApiGatewayRestApi
      REGION: '#{AWS::Region}'
      STAGE: ${opt:stage}
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
